# Generated by Django 3.2.9 on 2021-11-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20211121_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
