# Generated by Django 3.2.9 on 2021-12-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
