# Generated by Django 3.2.9 on 2021-12-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_time',)},
        ),
    ]
