# Generated by Django 3.2.9 on 2022-01-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='Текст к посту'),
        ),
    ]
