exclude: "^docs/|/migrations/|tasks.py"
default_stages: [commit]

repos:

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--settings-file=./server/setup.cfg"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=./server/setup.cfg"]